In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TopicosEspEng1/dados_reg.csv', sep=';', header=None)
df

0      1
0  2    7,6
1  3   21,4
2  5     79
3  6  125,2
4  8  258,4
5  2    7,6
6  4   44,8
7  5     79
8  8  258,4
9  2    7,6

In [ ]:
df.columns = ["X", "Y"]
df

X      Y
0  2    7,6
1  3   21,4
2  5     79
3  6  125,2
4  8  258,4
5  2    7,6
6  4   44,8
7  5     79
8  8  258,4
9  2    7,6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   X       10 non-null     int64 
 1   Y       10 non-null     object
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes


In [ ]:
df.Y = df.Y.str.replace(',', '.')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   X       10 non-null     int64 
 1   Y       10 non-null     object
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes


In [ ]:
df = df.apply(pd.to_numeric, errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X       10 non-null     int64  
 1   Y       10 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 292.0 bytes


In [ ]:
df1 = pd.DataFrame()
df1.x = df.X
df1.x

<ipython-input-16-71488b72e0a6>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df1.x = df.X


0    2
1    3
2    5
3    6
4    8
5    2
6    4
7    5
8    8
9    2
Name: X, dtype: int64

In [ ]:
df2 = pd.DataFrame()
df2["a"]=1
df2["x"]=df1.x
df2["x2"]=df1.x*df1.x
df2["x3"]=df1.x*df1.x*df1.x
df2["a"]=1
df2

a  x  x2   x3
0  1  2   4    8
1  1  3   9   27
2  1  5  25  125
3  1  6  36  216
4  1  8  64  512
5  1  2   4    8
6  1  4  16   64
7  1  5  25  125
8  1  8  64  512
9  1  2   4    8

In [ ]:
df1=pd.DataFrame()
df1.y=df.Y
df1.y

<ipython-input-22-df8bf1d432bb>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df1.y=df.Y


0      7.6
1     21.4
2     79.0
3    125.2
4    258.4
5      7.6
6     44.8
7     79.0
8    258.4
9      7.6
Name: Y, dtype: float64

In [ ]:
x=df2.to_numpy()
y=df1.y.to_numpy()

In [ ]:
print(x)

[[  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]
 [  1   6  36 216]
 [  1   8  64 512]
 [  1   2   4   8]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   8  64 512]
 [  1   2   4   8]]


In [ ]:
print(y)

[  7.6  21.4  79.  125.2 258.4   7.6  44.8  79.  258.4   7.6]


In [ ]:
B=np.linalg.inv(x.T@x)@x.T@y
B

array([ 4. , -5. ,  3. ,  0.2])

In [ ]:
dr = pd.read_csv('/content/drive/MyDrive/TopicosEspEng1/dados_reg2.csv', sep=';')
dr

x1  x2     y
0    5   6   282
1    8   8   931
2    5   5   223
3    6   4   279
4    7   2   374
5    9   9  1335
6    8   7   852
7    8   2   607
8    6   4   279
9    9   9  1335
10   8   2   607
11   9   3   951

In [ ]:
dr1 = pd.DataFrame()
dr1.x = dr.x1
dr1.x

<ipython-input-43-a68b73dc9c5a>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  dr1.x = dr.x1


0     5
1     8
2     5
3     6
4     7
5     9
6     8
7     8
8     6
9     9
10    8
11    9
Name: x1, dtype: int64

In [ ]:
dr2 = pd.DataFrame()
dr2["a"]=1
dr2["x1"]=dr1.x
dr2["x2"]=dr1.x*dr1.x
dr2["x.2"]=dr1.x*dr1.x
dr2["x.1"]=dr1.x*dr1.x*dr1.x
dr2["a"]=1
dr2

a  x1  x2  x.2  x.1
0   1   5  25   25  125
1   1   8  64   64  512
2   1   5  25   25  125
3   1   6  36   36  216
4   1   7  49   49  343
5   1   9  81   81  729
6   1   8  64   64  512
7   1   8  64   64  512
8   1   6  36   36  216
9   1   9  81   81  729
10  1   8  64   64  512
11  1   9  81   81  729

In [ ]:
dr1=pd.DataFrame()
dr1.y=dr.y
dr1.y

<ipython-input-46-4e30fdf4cac2>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  dr1.y=dr.y


0      282
1      931
2      223
3      279
4      374
5     1335
6      852
7      607
8      279
9     1335
10     607
11     951
Name: y, dtype: int64

In [ ]:
x=dr2.to_numpy()
y=dr1.y.to_numpy()

In [ ]:
print(x)
print(y)

[[  1   5  25  25 125]
 [  1   8  64  64 512]
 [  1   5  25  25 125]
 [  1   6  36  36 216]
 [  1   7  49  49 343]
 [  1   9  81  81 729]
 [  1   8  64  64 512]
 [  1   8  64  64 512]
 [  1   6  36  36 216]
 [  1   9  81  81 729]
 [  1   8  64  64 512]
 [  1   9  81  81 729]]
[ 282  931  223  279  374 1335  852  607  279 1335  607  951]
